name: "[CI] Continuous Integration"

on:
    pull_request:
        types: [opened, synchronize]

env:
    SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
    SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
            
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: "Debug"
              run: "ls -la"
            - name: "Install dependencies"
              run: "npm install"
            - name: "Running Lint"
              run: "npm run lint"

    tests:
        runs-on: ubuntu-latest
        container: cypress/browsers:node-20.14.0-chrome-126.0.6478.114-1-ff-127.0.1-edge-126.0.2592.61-1
        steps:
            - uses: actions/checkout@v4

            - name: "Install dependencies"
              run: "npm install"
            - name: "Running Application tests"
              run: "npm run test"
