name: "[CI] Continuous Integration"

on:
    pull_request:
        types: [opened, synchronize]

env:
    SUPABASE_URL: ${{ vars.SUPABASE_URL }}
    SUPABASE_KEY: ${{ vars.SUPABASE_KEY }}
            
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: "Debug"
              run: "ls -la"
            - name: "Install dependencies"
              run: "npm install"
            - name: "lint"
              run: "npm run lint"

    tests:
        runs-on: ubuntu-latest
        container: cypress/browsers:node-20.14.0-chrome-126.0.6478.114-1-ff-127.0.1-edge-126.0.2592.61-1
        steps:
            - uses: actions/checkout@v4

            - name: "Set up environment variables"
              run: |
                echo "Supabase Key: ${{ vars.SUPABASE_KEY }}"
                echo "Supabase URL: ${{ vars.SUPABASE_URL }}"

              env:
                SUPABASE_URL: ${{ vars.SUPABASE_URL }}
                SUPABASE_KEY: ${{ vars.SUPABASE_KEY }}

            # Install npm dependencies, cache them correctly
            # and run all Cypress tests
            - name: "Install dependencies"
              run: "npm install"
            - name: "tests"
              run: "npm run test"
                


            