name: "[CI] Continuous Integration"

# Sempre que tiver um commit ou PR for aberto, o CI será executado
on:
    pull_request:
        types: [opened, synchronize]
            
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Debug
              run: "ls -la"
            - name: lint
              run: "npm run lint"

            